// tiffport/src/pages/Connect/Connect.tsx
import './Connect.css'

export function Connect() {
  return (
    <div className="connect">
      <div className="connect-image">
        <img src="/11-1.thumb128.png" alt="hamster thumbnail" className="image-placeholder" />
      </div>
      <div className="connect-content">
        <h1 className="connect-name">tiffany lin</h1>
        <p className="connect-email">tiffqlin@gmail.com</p>
        <a href="https://www.linkedin.com/in/tiffanyqlin/" className="connect-linkedin">
          linkedin.com/in/tiffanyqlin
        </a>
      </div>
    </div>
  )
}

// tiffport/src/pages/Connect/Connect.vue
<template>
  <div class="connect">
    <div class="connect-image">
      <img src="/11-1.thumb128.png" alt="hamster thumbnail" class="image-placeholder" />
    </div>
    <div class="connect-content">
      <h1 class="connect-name">tiffany lin</h1>
      <p class="connect-email">tiffqlin@gmail.com</p>
      <a href="https://www.linkedin.com/in/tiffanyqlin/" class="connect-linkedin">
        linkedin.com/in/tiffanyqlin
      </a>
    </div>
  </div>
</template>

<script setup lang="ts">
</script>

<style>
@import './Connect.css';
</style>
