// tiffport/src/components/Layout/Layout.tsx
import { Outlet } from 'react-router-dom'
import { Navbar } from '../Navbar'
import './Layout.css'

interface LayoutProps {
  theme: 'light' | 'dark'
}

export function Layout({ theme }: LayoutProps) {
  return (
    <div className={`layout layout--${theme}`}>
      <Navbar />
      <main>
        <Outlet />
      </main>
    </div>
  )
}

// tiffport/src/components/Layout/Layout.vue
<template>
  <div class="layout" :class="{ 'layout--dark': route.meta.theme === 'dark' }">
    <Navbar v-if="route.path !== '/'" />
    <main>
      <router-view />
    </main>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'vue-router'
import Navbar from '../Navbar/Navbar.vue'

const route = useRoute()
</script>

<style>
@import './Layout.css';
</style>
