// tiffport/src/components/Navbar/Navbar.tsx
import { NavLink } from 'react-router-dom'
import './Navbar.css'

export function Navbar() {
  return (
    <nav className="navbar">
      <NavLink to="/" className="nav-link">HOME</NavLink>
      <NavLink to="/portfolio" className="nav-link">PORTFOLIO</NavLink>
      <NavLink to="/connect" className="nav-link">CONNECT</NavLink>
    </nav>
  )
}

// tiffport/src/components/Navbar/Navbar.vue
<template>
  <nav class="navbar">
    <router-link to="/" class="nav-link" exact>HOME</router-link>
    <router-link to="/portfolio" class="nav-link">PORTFOLIO</router-link>
    <router-link to="/connect" class="nav-link">CONNECT</router-link>
  </nav>
</template>

<script setup lang="ts">
</script>

<style>
@import './Navbar.css';
</style>
