// tiffport/src/pages/Home/Home.vue
<template>
  <div class="home">
    <div class="home-content">
      <h1 class="home-title">tiffany lin</h1>
      <nav class="home-nav">
        <router-link to="/portfolio" class="home-link">portfolio</router-link>
        <router-link to="/connect" class="home-link">connect</router-link>
      </nav>
    </div>
    <div class="home-image">
      <img src="/10-1.thumb128.png" alt="hamster thumbnail" class="image-placeholder" />
    </div>
  </div>
</template>

<script setup lang="ts">
</script>

<style>
@import './Home.css';
</style>

// tiffport/src/pages/Home/Home.tsx
import { Link } from 'react-router-dom'
import './Home.css'

export function Home() {
  return (
    <div className="home">
      <div className="home-content">
        <h1 className="home-title">tiffany lin</h1>
        <nav className="home-nav">
          <Link to="/portfolio" className="home-link">portfolio</Link>
          <Link to="/connect" className="home-link">connect</Link>
        </nav>
      </div>
      <div className="home-image">
        <img src="/10-1.thumb128.png" alt="hamster thumbnail" className="image-placeholder" />
      </div>
    </div>
  )
}
